### ISSUE TITLE
GUI TODO 

### ISSUE THREAD

**Issue by PawelCiupka** [jurczewski/CPS#1]
1. Strona na której wybieramy sygnał, podajemy parametry i rysujemy sygnał + histogram (+modyfikatory wyglądu histogramu). Dodatkowo wrzucić guziki: Rysuj wykres, Wczytaj wykres, Zapisz wykres + Wykonaj obliczenia.
2. Strona do wykonywania obliczeń na wykresach. Wybieranie dwóch plików z wykresami oraz interesującej nas operacji + rysowanie sygnału i histogramu.

**Comment by jurczewski** [comment]
Done.

**Comment by jurczewski** [comment]
Done.
